// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSHH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSHH'](arg1, arg2, arg3, arg4);
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}
