// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSHH(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function DisconnectSSH():Promise<void>;

export function IsConnected():Promise<boolean>;

export function RunCommand(arg1:string):Promise<string>;
